// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWQmVGUJp_8NwJpojUF2zZtVFk4XDQCY',
    appId: '1:459145001049:web:64b6db02dc83305898d948',
    messagingSenderId: '459145001049',
    projectId: 'drugs-addiction-detectio-41ad3',
    authDomain: 'drugs-addiction-detectio-41ad3.firebaseapp.com',
    storageBucket: 'drugs-addiction-detectio-41ad3.firebasestorage.app',
    measurementId: 'G-JB5R1WZRFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJ_AeBDIdDJvRirfU6Dpyfy3sPkaWe8o',
    appId: '1:459145001049:android:090233840351270c98d948',
    messagingSenderId: '459145001049',
    projectId: 'drugs-addiction-detectio-41ad3',
    storageBucket: 'drugs-addiction-detectio-41ad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTUuFj2G9K4abCnmOlbNPc_VPsTSbvUU',
    appId: '1:459145001049:ios:70b7194f81ae438798d948',
    messagingSenderId: '459145001049',
    projectId: 'drugs-addiction-detectio-41ad3',
    storageBucket: 'drugs-addiction-detectio-41ad3.firebasestorage.app',
    iosBundleId: 'com.example.drugsAddictionDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTUuFj2G9K4abCnmOlbNPc_VPsTSbvUU',
    appId: '1:459145001049:ios:70b7194f81ae438798d948',
    messagingSenderId: '459145001049',
    projectId: 'drugs-addiction-detectio-41ad3',
    storageBucket: 'drugs-addiction-detectio-41ad3.firebasestorage.app',
    iosBundleId: 'com.example.drugsAddictionDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNWQmVGUJp_8NwJpojUF2zZtVFk4XDQCY',
    appId: '1:459145001049:web:c80edceae051612598d948',
    messagingSenderId: '459145001049',
    projectId: 'drugs-addiction-detectio-41ad3',
    authDomain: 'drugs-addiction-detectio-41ad3.firebaseapp.com',
    storageBucket: 'drugs-addiction-detectio-41ad3.firebasestorage.app',
    measurementId: 'G-C5F1B9J12Y',
  );
}
